name: Build Video Converter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true
      
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: VideoConverter
        path: bin/Release/net6.0/win-x64/publish/VideoConverter.exe
